"""Add verified VinFast vehicle profiles.

Revision ID: 20260815_0130
Revises: 20260815_0010
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20260815_0130"
down_revision = "20260815_0010"
branch_labels = None
depends_on = None


PROFILE_IDS = (
    "vinfast-vf3-v1",
    "vinfast-vf5-plus-v1",
    "vinfast-vf6-eco-v1",
    "vinfast-vf7-eco-v1",
    "vinfast-vf7-plus-awd-v1",
    "vinfast-vf8-eco-catl-v1",
    "vinfast-vf8-plus-catl-v1",
)


def _profile(
    *,
    profile_id: str,
    version: str,
    name: str,
    battery_kwh: float,
    max_dc_kw: float,
    baseline_wh_km: float,
    derivation: str,
    reference_range_km: float,
    reference_standard: str,
    motor_kw: float,
    torque_nm: float,
    drive_type: str,
    seats: int,
    curb_weight_kg: float,
    dimensions_mm: str,
    wheelbase_mm: float,
    ground_clearance_mm: float,
    wheel_size_inch: float,
    fast_charge_min: float,
    official_source: str,
    brochure_range_km: float | None = None,
    brochure_standard: str | None = None,
) -> dict:
    curve = {
        "baseline_wh_per_km": baseline_wh_km,
        "baseline_derivation": derivation,
        "reference_range_km": reference_range_km,
        "reference_range_standard": reference_standard,
        "motor_power_kw": motor_kw,
        "max_torque_nm": torque_nm,
        "drive_type": drive_type,
        "seats": seats,
        "curb_weight_kg": curb_weight_kg,
        "dimensions_mm": dimensions_mm,
        "wheelbase_mm": wheelbase_mm,
        "ground_clearance_mm": ground_clearance_mm,
        "wheel_size_inch": wheel_size_inch,
        "fast_charge_10_70_min": fast_charge_min,
        "ambient_temperature_c": 25.0,
        "vehicle_payload_kg": 150.0,
        "terrain": "LIVE_OPEN_METEO_ELEVATION",
        "official_source": official_source,
    }
    if brochure_range_km is not None:
        curve["brochure_range_km"] = brochure_range_km
        curve["brochure_range_standard"] = brochure_standard
    return {
        "id": profile_id,
        "version": version,
        "name": name,
        "battery_capacity_kwh": battery_kwh,
        "usable_capacity_kwh": battery_kwh,
        "max_charging_power_kw": max_dc_kw,
        "connector_type": "CCS2",
        "consumption_curve_json": curve,
    }


def upgrade() -> None:
    vehicle_profiles = sa.table(
        "vehicle_profiles",
        sa.column("id", sa.String),
        sa.column("version", sa.String),
        sa.column("name", sa.String),
        sa.column("battery_capacity_kwh", sa.Float),
        sa.column("usable_capacity_kwh", sa.Float),
        sa.column("max_charging_power_kw", sa.Float),
        sa.column("connector_type", sa.String),
        sa.column("consumption_curve_json", sa.JSON),
    )
    op.bulk_insert(
        vehicle_profiles,
        [
            _profile(
                profile_id="vinfast-vf3-v1",
                version="vinfast_vf3_2025.1",
                name="VinFast VF 3",
                battery_kwh=18.64,
                max_dc_kw=24.0,
                baseline_wh_km=86.7,
                derivation="usable_capacity_kwh / official_NEDC_range_215km",
                reference_range_km=215.0,
                reference_standard="NEDC",
                motor_kw=30.0,
                torque_nm=110.0,
                drive_type="RWD / Cầu sau",
                seats=4,
                curb_weight_kg=857.0,
                dimensions_mm="3.190 × 1.679 × 1.652",
                wheelbase_mm=2075.0,
                ground_clearance_mm=175.0,
                wheel_size_inch=16.0,
                fast_charge_min=36.0,
                official_source="https://vinfastauto.com/vn_vi/cau-hoi-thuong-gap/cau-hoi-xe-o-to/san-pham/vf-3",
            ),
            _profile(
                profile_id="vinfast-vf5-plus-v1",
                version="vinfast_vf5_plus_2025.1",
                name="VinFast VF 5 Plus",
                battery_kwh=37.23,
                max_dc_kw=50.0,
                baseline_wh_km=114.2,
                derivation="usable_capacity_kwh / official_NEDC_range_326km",
                reference_range_km=326.0,
                reference_standard="NEDC",
                motor_kw=100.0,
                torque_nm=135.0,
                drive_type="FWD / Cầu trước",
                seats=5,
                curb_weight_kg=1340.0,
                dimensions_mm="3.967 × 1.723 × 1.579",
                wheelbase_mm=2514.0,
                ground_clearance_mm=160.0,
                wheel_size_inch=17.0,
                fast_charge_min=33.0,
                official_source="https://vinfastauto.com/vn_vi/cau-hoi-thuong-gap/cau-hoi-xe-o-to/san-pham/vf-5",
            ),
            _profile(
                profile_id="vinfast-vf6-eco-v1",
                version="vinfast_vf6_eco_2025.1",
                name="VinFast VF 6 Eco",
                battery_kwh=59.6,
                max_dc_kw=100.0,
                baseline_wh_km=149.4,
                derivation="usable_capacity_kwh / official_WLTP_range_399km",
                reference_range_km=399.0,
                reference_standard="WLTP",
                brochure_range_km=485.0,
                brochure_standard="NEDC",
                motor_kw=130.0,
                torque_nm=250.0,
                drive_type="FWD / Cầu trước",
                seats=5,
                curb_weight_kg=1743.0,
                dimensions_mm="4.241 × 1.834 × 1.580",
                wheelbase_mm=2730.0,
                ground_clearance_mm=170.0,
                wheel_size_inch=18.0,
                fast_charge_min=25.0,
                official_source="https://vinfastauto.com/vn_vi/cau-hoi-thuong-gap/cau-hoi-xe-o-to/san-pham/vf-6",
            ),
            _profile(
                profile_id="vinfast-vf7-eco-v1",
                version="vinfast_vf7_eco_2024.1",
                name="VinFast VF 7 Eco (2024)",
                battery_kwh=59.6,
                max_dc_kw=110.0,
                baseline_wh_km=158.9,
                derivation="usable_capacity_kwh / official_WLTP_range_375km",
                reference_range_km=375.0,
                reference_standard="WLTP",
                brochure_range_km=430.0,
                brochure_standard="NEDC",
                motor_kw=130.0,
                torque_nm=250.0,
                drive_type="FWD / Cầu trước",
                seats=5,
                curb_weight_kg=2085.0,
                dimensions_mm="4.545 × 1.890 × 1.635,75",
                wheelbase_mm=2840.0,
                ground_clearance_mm=190.0,
                wheel_size_inch=19.0,
                fast_charge_min=25.0,
                official_source="https://vinfastauto.com/vn_vi/thong-so-vf-7",
            ),
            _profile(
                profile_id="vinfast-vf7-plus-awd-v1",
                version="vinfast_vf7_plus_awd_2024.1",
                name="VinFast VF 7 Plus AWD (2024)",
                battery_kwh=75.3,
                max_dc_kw=110.0,
                baseline_wh_km=174.7,
                derivation="usable_capacity_kwh / official_WLTP_range_431km",
                reference_range_km=431.0,
                reference_standard="WLTP",
                brochure_range_km=496.0,
                brochure_standard="NEDC",
                motor_kw=260.0,
                torque_nm=500.0,
                drive_type="AWD / Hai cầu",
                seats=5,
                curb_weight_kg=2205.0,
                dimensions_mm="4.545 × 1.890 × 1.635,75",
                wheelbase_mm=2840.0,
                ground_clearance_mm=190.0,
                wheel_size_inch=20.0,
                fast_charge_min=37.0,
                official_source="https://vinfastauto.com/vn_vi/thong-so-vf-7",
            ),
            _profile(
                profile_id="vinfast-vf8-eco-catl-v1",
                version="vinfast_vf8_eco_catl_2024.1",
                name="VinFast VF 8 Eco CATL",
                battery_kwh=87.7,
                max_dc_kw=149.0,
                baseline_wh_km=186.2,
                derivation="usable_capacity_kwh / official_WLTP_range_471km",
                reference_range_km=471.0,
                reference_standard="WLTP",
                motor_kw=260.0,
                torque_nm=500.0,
                drive_type="AWD / Hai cầu",
                seats=5,
                curb_weight_kg=2455.0,
                dimensions_mm="4.750 × 1.934 × 1.667",
                wheelbase_mm=2950.0,
                ground_clearance_mm=175.0,
                wheel_size_inch=19.0,
                fast_charge_min=31.0,
                official_source="https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw006b4dec/raisinghands/documents/VF8_Brochure_VN.pdf",
            ),
            _profile(
                profile_id="vinfast-vf8-plus-catl-v1",
                version="vinfast_vf8_plus_catl_2024.1",
                name="VinFast VF 8 Plus CATL",
                battery_kwh=87.7,
                max_dc_kw=149.0,
                baseline_wh_km=191.9,
                derivation="usable_capacity_kwh / official_WLTP_range_457km",
                reference_range_km=457.0,
                reference_standard="WLTP",
                motor_kw=300.0,
                torque_nm=620.0,
                drive_type="AWD / Hai cầu",
                seats=5,
                curb_weight_kg=2520.0,
                dimensions_mm="4.750 × 1.934 × 1.667",
                wheelbase_mm=2950.0,
                ground_clearance_mm=175.0,
                wheel_size_inch=20.0,
                fast_charge_min=31.0,
                official_source="https://shop.vinfastauto.com/on/demandware.static/-/Sites-app_vinfast_vn-Library/default/dw006b4dec/raisinghands/documents/VF8_Brochure_VN.pdf",
            ),
        ],
    )


def downgrade() -> None:
    vehicle_profiles = sa.table("vehicle_profiles", sa.column("id", sa.String))
    op.execute(sa.delete(vehicle_profiles).where(vehicle_profiles.c.id.in_(PROFILE_IDS)))
