from enum import StrEnum


class PlanningOutcomeKind(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    INFEASIBLE = "INFEASIBLE"
    REQUIRES_USER_ACTION = "REQUIRES_USER_ACTION"
    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
